package:
  name: q2-viromics
  version: {{ PLUGIN_VERSION }}

source:
  path: ..

build:
  script: make install

requirements:
  host:
    - python {{ python }}
    - setuptools
    - versioningit
    - wheel

  run:
    - qiime2 {{ qiime2_epoch }}.*
    - q2-metadata {{ qiime2_epoch }}.*
    - q2-types {{ qiime2_epoch }}.*
    - checkv
    - pyhmmer

test:
  requires:
    - parameterized
  imports:
    - q2_viromics
    - qiime2.plugins.viromics
  commands:
    - pytest --pyargs q2_viromics

about:
  home: https://github.com/bokulich-lab/q2-viromics
  license: BSD-3-Clause
  license_family: BSD
