name: CI
on:
  pull_request:
    branches: ["main"]
  push:
    branches: ["main"]

jobs:
  ci:
    uses: bokulich-lab/utilities/.github/workflows/ci.yaml@main
    with:
      distro: pathogenome

  qiime-ci:
    uses: qiime2/distributions/.github/workflows/lib-ci-dev.yaml@dev
    with:
      distro: pathogenome
      recipe-path: 'conda-recipe'
